version = 1

[[annotations]]
path = ["Cargo.lock", "fuzz/Cargo.lock"]
precedence = "override"
SPDX-FileCopyrightText = "2026 Yasunobu Sakashita"
SPDX-License-Identifier = "MIT OR Apache-2.0"

[[annotations]]
path = ["fuzz/corpus/**", "fuzz/terminfo.dict", "oracle/ncurses-6.6.lock"]
precedence = "override"
SPDX-FileCopyrightText = "2026 Yasunobu Sakashita"
SPDX-License-Identifier = "MIT OR Apache-2.0"

[[annotations]]
path = ".github/workflows/v-release.yml"
precedence = "override"
SPDX-FileCopyrightText = "2022-2024 axodotdev"
SPDX-License-Identifier = "MIT OR Apache-2.0"
