# SPDX-FileCopyrightText: 2026 Yasunobu Sakashita
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "terminfokit"
description = "Terminfo parsing, compilation, formatting, database access, and expansion"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license = "(MIT OR Apache-2.0) AND X11"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
publish = ["crates-io"]
readme = "README.md"
documentation = "https://docs.rs/terminfokit"
keywords = ["terminfo", "tic", "infocmp", "curses", "terminal"]
categories = ["command-line-interface", "parser-implementations", "no-std"]

[features]
default = ["std"]
std = ["dep:atomic-write-file"]

[dependencies]
atomic-write-file = { version = "0.3", default-features = false, optional = true }

[package.metadata.docs.rs]
all-features = true
